### ISSUE TITLE
Incorrect folder name when downloading from e107.org

### ISSUE THREAD

**Issue by LaocheXe** [septor/anteup#30] opened 2015-11-22 18:40 UTC
Up top for the title (Admin Area -> Plugin Prefs of AnteUp) I see LAN_ANTEUP_PREFERNCES

Also when plugin isn't installed you get LAN_ANTEUP_NAME

I think you are missing the good ol' include_lan(e_PLUGIN.'anteup-master/languages/'.e_LANGUAGE.'.php'); in the admin_config.php

**Comment by LaocheXe** [comment] 2015-11-22 18:47
Update: looking over the admin_config.php I notice an issue. line 52: protected $pluginName		= 'anteup';

that is for the folder name, that  Jimmi08  pointed out to me in another plugin I was working on. you have it as anteup but the plugin from e107 site extracts the file as anteup-master

Reason why the LAN's show up weird and some other issues I found in the preferences area. renaming the folder to just anteup fix the issues.

**Comment by Moc** [comment] 2015-11-22 19:38
This is a Github issue, it adds the branch (master) to the repository name (anteup-master). The plugin folder name should be anteup.

**Comment by Moc** [comment] 2015-11-23 09:19
@septor On the e107.org plugin upload, you can change the uploaded zip file to extract a folder called anteup and not anteup-master. 

(@LaocheXe - sorry, I missed that you reported this specifically, it should indeed be fixed on e107.org)

**Comment by septor** [comment] 2015-11-23 10:20
The one time I forget to change the folder name before adding the zip to the release page happens to be on the one plugin I upload to e107.org...

I'll get it fixed ASAP. For now, as @Moc said, you'll have to rename the folder.

Sorry. :(

**Comment by septor** [comment] 2015-11-26 15:51
An update on this:

I've updated the zip file on the release page of the repo. I cannot update the zip file on e107.org until I release a new version (which won't happen for awhile). I'll add contacting Cameron to my list of things to do, but I wouldn't count on it getting very far (because I'm kind of lazy).

I've learned 2 things from this adventure:

1. Double check folder structure before zipping and uploading to places (here, and e107.org).
2. Don't bother with the e107.org upload gizmo until it's possible to modify/update plugins.

**Comment by septor** [comment] 2015-11-27 10:32
Another update:

I've email Cameron and the issue is getting resolved as of this writing. I'll leave this issue open until the zip file is fixed. Since yesterday was a holiday here in the States, I don't personally expect it to get taken care of until Monday.

Sorry for the inconveniences!

**Comment by septor** [comment] 2015-12-01 11:47
The zip on e107.org has been fixed and now contains the correct folder naming scheme.

**Closed by septor** 2015-12-01 11:47 UTC
Labels: enhancement
