### ISSUE TITLE
Issue: donations.php Typo

### ISSUE THREAD

**Issue by LaocheXe** [septor/anteup#32] opened 2016-01-14 22:50 UTC
http://clancoyote.com/main/e107_plugins/anteup/donations.php

The donations .php I believe has a typo, it list the first date, January 5th 2017 and the second date as January 30th 2016 - that a type or am I nuts?

**Comment by septor** [comment] 2016-01-15 17:33
The default range is your last due date to your current due date, both are picked configured in the preferences area.

https://github.com/septor/anteup/blob/master/donations.php#L24
https://github.com/septor/anteup/blob/master/donations.php#L25

**Comment by LaocheXe** [comment] 2016-01-15 17:52
Odd - in admin area for the plugin - prefs - Due date is set to Saturday, 30 Jan, 2016 and Previous Due date is Thursday, 31 Dec, 2015.

In the donations.php page shows Thursday, 05 January, 2017 and then Saturday, 30 January, 2016

What I don't understand is the January, 2017 - shouldn't that be December, 2015?

**Comment by septor** [comment] 2016-01-17 04:36
This seems related to this somehow: https://github.com/septor/dateplus/issues/1

More investigation is called for.

**Comment by Moc** [comment] 2016-12-27 13:18
Confirmed, it's caused by an issue in the datepicker method in e107 core. 
Debug in progress.

**Comment by Moc** [comment] 2017-01-02 14:57
This should be fixed using the latest Github files. Please confirm @LaocheXe

**Closed** 2017-01-02 16:00 UTC
Labels: bug
